INTEGRATION_CATALOG = {
    "openai": {"name": "OpenAI / ChatGPT models", "category": "ai", "description": "Writing, directing, visual-development, speech, and production assistants.", "capabilities": ["text", "structured output", "image", "speech"], "default_endpoint": "https://api.openai.com/v1", "default_model": "gpt-5.6-terra", "secret_env_var": "KIZUNA_OPENAI_API_KEY", "modes": ["api", "disabled"]},
    "anthropic": {"name": "Claude", "category": "ai", "description": "Story, analysis, production planning, and long-context creative work.", "capabilities": ["text", "structured output", "vision"], "default_endpoint": "https://api.anthropic.com", "default_model": "", "secret_env_var": "KIZUNA_ANTHROPIC_API_KEY", "modes": ["api", "disabled"]},
    "google": {"name": "Gemini", "category": "ai", "description": "Multimodal writing, analysis, image understanding, and generation workflows.", "capabilities": ["text", "structured output", "vision", "image"], "default_endpoint": "https://generativelanguage.googleapis.com", "default_model": "", "secret_env_var": "KIZUNA_GOOGLE_API_KEY", "modes": ["api", "disabled"]},
    "ollama": {"name": "Ollama", "category": "ai", "description": "Local and private language or vision models running on your own hardware.", "capabilities": ["text", "structured output", "vision", "local"], "default_endpoint": "http://127.0.0.1:11434", "default_model": "", "secret_env_var": "", "modes": ["api", "disabled"]},
    "custom-ai": {"name": "Custom AI API", "category": "ai", "description": "An OpenAI-compatible or homebrew HTTP service controlled by your studio.", "capabilities": ["custom", "self-hosted"], "default_endpoint": "", "default_model": "", "secret_env_var": "KIZUNA_CUSTOM_AI_API_KEY", "modes": ["api", "disabled"]},
    "comfyui": {"name": "ComfyUI", "category": "generation", "description": "Node-based image and animation workflows on local or network GPUs.", "capabilities": ["image", "animation", "upscale", "ControlNet"], "default_endpoint": "http://127.0.0.1:8188", "default_model": "", "secret_env_var": "", "modes": ["api", "disabled"]},
    "automatic1111": {"name": "AUTOMATIC1111 / Forge", "category": "generation", "description": "Stable Diffusion image generation through a familiar web UI and API.", "capabilities": ["image", "inpaint", "upscale"], "default_endpoint": "http://127.0.0.1:7860", "default_model": "", "secret_env_var": "", "modes": ["api", "handoff", "disabled"]},
    "invokeai": {"name": "InvokeAI", "category": "generation", "description": "Canvas-driven local image generation and controlled visual iteration.", "capabilities": ["image", "canvas", "inpaint"], "default_endpoint": "http://127.0.0.1:9090", "default_model": "", "secret_env_var": "", "modes": ["api", "handoff", "disabled"]},
    "adobe": {"name": "Adobe Creative Cloud", "category": "creative", "description": "Exchange storyboards, layered art, audio, timelines, and masters with Adobe tools.", "capabilities": ["PSD", "Premiere", "After Effects", "Audition"], "default_endpoint": "", "default_model": "", "secret_env_var": "", "modes": ["handoff", "disabled"]},
    "corel": {"name": "Corel", "category": "creative", "description": "Hand off model sheets, backgrounds, and painted assets to CorelDRAW or Painter.", "capabilities": ["illustration", "painting", "layered files"], "default_endpoint": "", "default_model": "", "secret_env_var": "", "modes": ["handoff", "disabled"]},
    "gimp": {"name": "GIMP", "category": "creative", "description": "Open-source image cleanup, paintovers, masks, and layered asset exchange.", "capabilities": ["image editing", "XCF", "PSD"], "default_endpoint": "", "default_model": "", "secret_env_var": "", "modes": ["handoff", "disabled"]},
    "krita": {"name": "Krita", "category": "creative", "description": "Open-source drawing, frame animation, paintovers, and storyboard refinement.", "capabilities": ["drawing", "animation", "storyboard"], "default_endpoint": "", "default_model": "", "secret_env_var": "", "modes": ["handoff", "disabled"]},
    "opentoonz": {"name": "OpenToonz", "category": "creative", "description": "Open-source 2D animation handoff for drawings, exposure sheets, and scenes.", "capabilities": ["2D animation", "Xsheet", "cleanup"], "default_endpoint": "", "default_model": "", "secret_env_var": "", "modes": ["handoff", "disabled"]},
    "blender": {"name": "Blender", "category": "creative", "description": "3D layout, Grease Pencil, camera blocking, effects, and rendering exchange.", "capabilities": ["3D", "Grease Pencil", "camera", "VFX"], "default_endpoint": "", "default_model": "", "secret_env_var": "", "modes": ["handoff", "disabled"]},
    "davinci": {"name": "DaVinci Resolve", "category": "creative", "description": "Timeline, color, Fusion, audio, and final mastering handoff.", "capabilities": ["edit", "color", "Fusion", "Fairlight"], "default_endpoint": "", "default_model": "", "secret_env_var": "", "modes": ["handoff", "disabled"]},
}

CATEGORY_LABELS = {"ai": "AI engines", "generation": "Generation tools", "creative": "Creative applications"}
