(() => {
  const safe = value => String(value ?? '').replace(/[&<>"']/g, character => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[character]));
  const csrf = () => document.cookie.split('; ').find(item => item.startsWith('kizuna_marketing_csrf='))?.split('=')[1] || '';
  let data = {posts:[],beta:[],tickets:[],ops:[],ops_config:{},account_steward:{records:[]}};
  const request = async (url, options={}) => { const response=await fetch(url,{...options,headers:{'Content-Type':'application/json','X-Kizuna-CSRF':csrf(),...(options.headers||{})}}); if(response.status===204)return null; const body=await response.json().catch(()=>({})); if(!response.ok)throw new Error(body.detail||'Request failed'); return body; };
  const loginPanel=document.querySelector('[data-login]'),admin=document.querySelector('[data-admin]'),logout=document.querySelector('[data-logout]');
  document.querySelector('[data-login] form').addEventListener('submit',async event=>{event.preventDefault();const result=event.currentTarget.querySelector('[role="status"]');try{await request('/api/admin/login',{method:'POST',body:JSON.stringify({password:event.currentTarget.elements.password.value})});await load();}catch(error){result.textContent=error.message;}});
  logout.addEventListener('click',async()=>{await request('/api/admin/logout',{method:'POST'});location.reload();});
  async function load(){try{data=await request('/api/admin/overview');loginPanel.hidden=true;admin.hidden=false;logout.hidden=false;render();}catch{loginPanel.hidden=false;admin.hidden=true;logout.hidden=true;}}
  function render(){document.querySelector('[data-beta-count]').textContent=data.beta.filter(item=>item.status==='new').length;document.querySelector('[data-ticket-count]').textContent=data.tickets.filter(item=>item.status==='open').length;document.querySelector('[data-ops-count]').textContent=data.ops.filter(item=>item.needs_human&&item.status==='needs_review').length;renderOps();renderPosts();renderBeta();renderTickets();}
  document.querySelectorAll('[data-view]').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('[data-view]').forEach(item=>item.classList.toggle('active',item===button));document.querySelectorAll('[data-pane]').forEach(pane=>pane.hidden=pane.dataset.pane!==button.dataset.view);}));
  function renderOps(){const config=data.ops_config||{},needs=data.ops.filter(item=>item.needs_human&&item.status==='needs_review'),done=data.ops.filter(item=>['completed','auto_completed'].includes(item.status));document.querySelector('[data-ops-status]').innerHTML=`<b>${safe((config.mode||'assist').toUpperCase())}</b><span>${config.provider_ready?`${safe(config.protocol)} · ${safe(config.model)}`:'Built-in policy engine'}</span><span>${config.email_ready?'Email connected':'Email not connected'}</span><span>${safe(config.auto_confidence||85)}% auto-action threshold</span>`;document.querySelector('[data-ops-summary]').innerHTML=`<article><strong>${needs.length}</strong><span>Needs you</span></article><article><strong>${data.ops.filter(item=>item.status==='prepared').length}</strong><span>Prepared</span></article><article><strong>${done.length}</strong><span>Completed</span></article><article><strong>${data.ops.reduce((sum,item)=>sum+(item.input_tokens||0)+(item.output_tokens||0),0)}</strong><span>AI tokens</span></article>`;document.querySelector('[data-ops-list]').innerHTML=data.ops.map(opsCard).join('')||'<div class="item-card">No operations work yet. New beta applications and tickets will appear here automatically.</div>';wireOps();}
  function opsCard(item){const action=item.status==='needs_review'||item.status==='prepared';return `<article class="ops-card ${item.needs_human?'needs-human':''}"><header><div><span>${safe(item.agent)}</span><span>${safe(item.entity_type)} #${item.entity_id}</span><span>${safe(item.risk)} risk</span></div><b>${Math.round(item.confidence)}% confidence</b></header><h3>${safe(item.summary)}</h3><p>${safe(item.recommended_action)}</p><details><summary>Prepared response</summary><textarea rows="6" data-ops-response>${safe(item.draft_response)}</textarea></details><footer><small>${safe(item.provider)} · ${safe(item.status)}</small>${action?`<button data-execute-ops="${item.id}" ${!data.ops_config.email_ready?'disabled title="Connect email first"':''}>Approve & send</button>`:''}</footer>${item.provider_error?`<small class="ops-error">AI provider fallback: ${safe(item.provider_error)}</small>`:''}</article>`;}
  function wireOps(){document.querySelectorAll('[data-execute-ops]').forEach(button=>button.onclick=async()=>{const card=button.closest('.ops-card'),response=card.querySelector('[data-ops-response]').value;button.disabled=true;try{await request(`/api/admin/ops/${button.dataset.executeOps}/execute`,{method:'POST',body:JSON.stringify({response})});data=await request('/api/admin/overview');render();}catch(error){button.disabled=false;card.insertAdjacentHTML('beforeend',`<small class="ops-error">${safe(error.message)}</small>`);}});}
  document.querySelector('[data-run-ops]').onclick=async event=>{event.currentTarget.disabled=true;try{await request('/api/admin/ops/run',{method:'POST',body:'{}'});data=await request('/api/admin/overview');render();}finally{event.currentTarget.disabled=false;}};
  const postForm=document.querySelector('[data-post-form]');
  function renderPosts(){document.querySelector('[data-post-list]').innerHTML=data.posts.map(post=>`<article class="item-card" data-edit-post="${post.id}"><b>${safe(post.title)}</b><small>${safe(post.category)} · Updated ${new Date(post.updated_at).toLocaleDateString()}</small><span>${safe(post.status)}</span></article>`).join('')||'<div class="item-card">No posts yet.</div>';document.querySelectorAll('[data-edit-post]').forEach(card=>card.onclick=()=>editPost(Number(card.dataset.editPost)));}
  function editPost(id=null){const post=data.posts.find(item=>item.id===id);postForm.hidden=false;postForm.reset();postForm.elements.id.value=post?.id||'';postForm.elements.title.value=post?.title||'';postForm.elements.slug.value=post?.slug||'';postForm.elements.category.value=post?.category||'Studio notes';postForm.elements.excerpt.value=post?.excerpt||'';postForm.elements.body.value=post?.body||'';postForm.elements.author.value=post?.author||'Kizuna Studio';postForm.elements.status.value=post?.status||'draft';postForm.elements.featured.checked=Boolean(post?.featured);document.querySelector('[data-editor-title]').textContent=post?'Edit post':'New post';document.querySelector('[data-delete-post]').hidden=!post;}
  document.querySelector('[data-new-post]').onclick=()=>editPost();document.querySelector('[data-cancel-post]').onclick=()=>postForm.hidden=true;
  postForm.addEventListener('submit',async event=>{event.preventDefault();const form=event.currentTarget,id=form.elements.id.value,payload={title:form.elements.title.value,slug:form.elements.slug.value,category:form.elements.category.value,excerpt:form.elements.excerpt.value,body:form.elements.body.value,author:form.elements.author.value,status:form.elements.status.value,featured:form.elements.featured.checked};try{await request(id?`/api/admin/posts/${id}`:'/api/admin/posts',{method:id?'PUT':'POST',body:JSON.stringify(payload)});data=await request('/api/admin/overview');render();editPost(id?Number(id):data.posts[0]?.id);form.querySelector('.result').textContent='Saved.';}catch(error){form.querySelector('.result').textContent=error.message;}});
  document.querySelector('[data-delete-post]').onclick=async()=>{const id=postForm.elements.id.value;if(!id||!confirm('Delete this post? This cannot be undone.'))return;await request(`/api/admin/posts/${id}`,{method:'DELETE'});data=await request('/api/admin/overview');postForm.hidden=true;render();};
  function triageCard(item,type){
    const beta=type==='beta',options=beta?['new','reviewing','invited','waitlisted','closed']:['open','investigating','resolved','closed'];
    const steward=data.account_steward||{records:[]},provisioning=beta?(steward.records||[]).find(record=>record.application_id===item.id):null;
    const accountState=beta?(provisioning?`<small>Account Steward: ${safe(provisioning.status)}${provisioning.error?` · ${safe(provisioning.error)}`:''}</small>`:`<small>Account Steward: ${steward.ready?'ready':'not connected'}</small>`):'';
    const invite=beta&&item.status!=='invited'?`<button type="button" data-beta-invite="${item.id}" ${!steward.ready?'disabled title="Connect Account Steward first"':''}>Invite to beta</button>`:'';
    return `<article class="triage-card"><div><header><span>${safe(beta?item.experience:item.severity)}</span><span>${safe(beta?item.creator_type:item.category)}</span><small>${new Date(item.created_at).toLocaleString()}</small></header><h3>${safe(beta?item.name:item.reference+' · '+item.subject)}</h3><small>${safe(item.email)}</small><p>${safe(beta?item.project_summary:item.description)}</p>${beta&&item.desired_outcome?`<p><b>Desired outcome:</b> ${safe(item.desired_outcome)}</p>`:''}${!beta&&item.environment?`<small>${safe(item.environment)}</small>`:''}${accountState}</div><form data-triage="${type}" data-id="${item.id}"><select name="status">${options.map(option=>`<option value="${option}" ${item.status===option?'selected':''}>${option}</option>`).join('')}</select><textarea name="notes" rows="4" placeholder="Private admin notes">${safe(item.notes)}</textarea><div>${invite}<button type="submit">Save</button></div><div class="result"></div></form></article>`;
  }
  function wireTriage(){
    document.querySelectorAll('[data-triage]').forEach(form=>form.onsubmit=async event=>{event.preventDefault();const type=form.dataset.triage;try{await request(`/api/admin/${type}/${form.dataset.id}`,{method:'PUT',body:JSON.stringify({status:form.elements.status.value,notes:form.elements.notes.value})});form.querySelector('.result').textContent='Saved.';data=await request('/api/admin/overview');render();}catch(error){form.querySelector('.result').textContent=error.message;}});
    document.querySelectorAll('[data-beta-invite]').forEach(button=>button.onclick=async()=>{const form=button.closest('form'),result=form.querySelector('.result');button.disabled=true;result.textContent='Creating a secure invitation…';try{await request(`/api/admin/beta/${button.dataset.betaInvite}/invite`,{method:'POST',body:'{}'});data=await request('/api/admin/overview');render();}catch(error){button.disabled=false;result.textContent=error.message;}});
  }
  function renderBeta(){const filter=document.querySelector('[data-beta-filter]').value;document.querySelector('[data-beta-list]').innerHTML=data.beta.filter(item=>!filter||item.status===filter).map(item=>triageCard(item,'beta')).join('')||'<div class="item-card">No matching applicants.</div>';wireTriage();}
  function renderTickets(){const filter=document.querySelector('[data-ticket-filter]').value;document.querySelector('[data-ticket-list]').innerHTML=data.tickets.filter(item=>!filter||item.status===filter).map(item=>triageCard(item,'tickets')).join('')||'<div class="item-card">No matching tickets.</div>';wireTriage();}
  document.querySelector('[data-beta-filter]').onchange=renderBeta;document.querySelector('[data-ticket-filter]').onchange=renderTickets;load();
})();
