(() => {
  const safe = value => String(value ?? '').replace(/[&<>"']/g, character => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[character]));
  const csrf = () => document.cookie.split('; ').find(item => item.startsWith('kizuna_marketing_csrf='))?.split('=')[1] || '';
  let data = {posts:[],campaigns:[],beta:[],tickets:[],ops:[],digests:[],ops_config:{},digest_config:{},account_steward:{records:[]}},currentDigestId=null;
  const request = async (url, options={}) => { const response=await fetch(url,{...options,headers:{'Content-Type':'application/json','X-Kizuna-CSRF':csrf(),...(options.headers||{})}}); if(response.status===204)return null; const body=await response.json().catch(()=>({})); if(!response.ok)throw new Error(body.detail||'Request failed'); return body; };
  const loginPanel=document.querySelector('[data-login]'),admin=document.querySelector('[data-admin]'),logout=document.querySelector('[data-logout]');
  document.querySelector('[data-login] form').addEventListener('submit',async event=>{event.preventDefault();const result=event.currentTarget.querySelector('[role="status"]');try{await request('/api/admin/login',{method:'POST',body:JSON.stringify({password:event.currentTarget.elements.password.value})});await load();}catch(error){result.textContent=error.message;}});
  logout.addEventListener('click',async()=>{await request('/api/admin/logout',{method:'POST'});location.reload();});
  async function load(){try{data=await request('/api/admin/overview');loginPanel.hidden=true;admin.hidden=false;logout.hidden=false;render();}catch{loginPanel.hidden=false;admin.hidden=true;logout.hidden=true;}}
  function render(){document.querySelector('[data-beta-count]').textContent=data.beta.filter(item=>item.status==='new').length;document.querySelector('[data-ticket-count]').textContent=data.tickets.filter(item=>item.status==='open').length;document.querySelector('[data-ops-count]').textContent=data.ops.filter(item=>item.needs_human&&item.status==='needs_review').length;renderOps();renderDigests();renderCampaigns();renderPosts();renderBeta();renderTickets();}
  document.querySelectorAll('[data-view]').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('[data-view]').forEach(item=>item.classList.toggle('active',item===button));document.querySelectorAll('[data-pane]').forEach(pane=>pane.hidden=pane.dataset.pane!==button.dataset.view);}));
  function renderOps(){const config=data.ops_config||{},needs=data.ops.filter(item=>item.needs_human&&item.status==='needs_review'),done=data.ops.filter(item=>['completed','auto_completed'].includes(item.status));document.querySelector('[data-ops-status]').innerHTML=`<b>${safe((config.mode||'assist').toUpperCase())}</b><span>${config.provider_ready?`${safe(config.protocol)} · ${safe(config.model)}`:'Built-in policy engine'}</span><span>${config.email_ready?'Email connected':'Email not connected'}</span><span>${safe(config.auto_confidence||85)}% auto-action threshold</span>`;document.querySelector('[data-ops-summary]').innerHTML=`<article><strong>${needs.length}</strong><span>Needs you</span></article><article><strong>${data.ops.filter(item=>item.status==='prepared').length}</strong><span>Prepared</span></article><article><strong>${done.length}</strong><span>Completed</span></article><article><strong>${data.ops.reduce((sum,item)=>sum+(item.input_tokens||0)+(item.output_tokens||0),0)}</strong><span>AI tokens</span></article>`;document.querySelector('[data-ops-list]').innerHTML=data.ops.map(opsCard).join('')||'<div class="item-card">No operations work yet. New beta applications and tickets will appear here automatically.</div>';wireOps();}
  function opsCard(item){const action=item.status==='needs_review'||item.status==='prepared';return `<article class="ops-card ${item.needs_human?'needs-human':''}"><header><div><span>${safe(item.agent)}</span><span>${safe(item.entity_type)} #${item.entity_id}</span><span>${safe(item.risk)} risk</span></div><b>${Math.round(item.confidence)}% confidence</b></header><h3>${safe(item.summary)}</h3><p>${safe(item.recommended_action)}</p><details><summary>Prepared response</summary><textarea rows="6" data-ops-response>${safe(item.draft_response)}</textarea></details><footer><small>${safe(item.provider)} · ${safe(item.status)}</small>${action?`<button data-execute-ops="${item.id}" ${!data.ops_config.email_ready?'disabled title="Connect email first"':''}>Approve & send</button>`:''}</footer>${item.provider_error?`<small class="ops-error">AI provider fallback: ${safe(item.provider_error)}</small>`:''}</article>`;}
  function wireOps(){document.querySelectorAll('[data-execute-ops]').forEach(button=>button.onclick=async()=>{const card=button.closest('.ops-card'),response=card.querySelector('[data-ops-response]').value;button.disabled=true;try{await request(`/api/admin/ops/${button.dataset.executeOps}/execute`,{method:'POST',body:JSON.stringify({response})});data=await request('/api/admin/overview');render();}catch(error){button.disabled=false;card.insertAdjacentHTML('beforeend',`<small class="ops-error">${safe(error.message)}</small>`);}});}
  document.querySelector('[data-run-ops]').onclick=async event=>{event.currentTarget.disabled=true;try{await request('/api/admin/ops/run',{method:'POST',body:'{}'});data=await request('/api/admin/overview');render();}finally{event.currentTarget.disabled=false;}};
  function digestCard(item){const snapshot=item.snapshot||{},config=data.digest_config||{},canSend=item.status!=='sent'&&config.email_ready&&config.recipient_ready;return `<article class="digest-card"><header><div><span>${safe(item.status)}</span><span>${new Date(item.period_end).toLocaleString()}</span></div><small>${item.status==='sent'&&item.recipient?`Sent to ${safe(item.recipient)}`:'Private preview'}</small></header><div class="digest-metrics"><article><strong>${snapshot.urgent_decisions||0}</strong><span>Needs you</span></article><article><strong>${snapshot.blocked_customers||0}</strong><span>At risk</span></article><article><strong>${snapshot.editorial_review||0}</strong><span>Editorial review</span></article><article><strong>${snapshot.ai_tokens||0}</strong><span>AI tokens</span></article></div><label>Digest preview<textarea rows="22" data-digest-body>${safe(item.body)}</textarea></label><footer><small>${config.email_ready?(config.recipient_ready?`Delivery ready · ${safe(config.recipient_hint)}`:'Add the digest recipient setting'):'Connect SMTP to send'}</small>${item.status==='sent'?'<span>Delivered</span>':`<button class="primary" data-send-digest="${item.id}" ${!canSend?'disabled':''}>Review & send</button>`}</footer>${item.error?`<div class="ops-error">${safe(item.error)}</div>`:''}</article>`;}
  function renderDigests(){const current=data.digests.find(item=>item.id===currentDigestId)||data.digests[0];currentDigestId=current?.id||null;document.querySelector('[data-digest-status]').innerHTML=`<b>MANUAL REVIEW</b><span>${data.digest_config?.email_ready?'Email connected':'Email not connected'}</span><span>${data.digest_config?.recipient_ready?`Recipient ${safe(data.digest_config.recipient_hint)}`:'Recipient not configured'}</span><span>No private request text included</span>`;document.querySelector('[data-digest-current]').innerHTML=current?digestCard(current):'<div class="item-card">No digest yet. Prepare today’s brief when you are ready.</div>';document.querySelector('[data-digest-history]').innerHTML=data.digests.map(item=>`<button class="item-card digest-history-item" data-digest-select="${item.id}"><b>${new Date(item.period_end).toLocaleDateString()}</b><small>${safe(item.status)} · ${item.snapshot?.urgent_decisions||0} needs you</small></button>`).join('')||'<div class="item-card">History will appear here.</div>';document.querySelectorAll('[data-digest-select]').forEach(button=>button.onclick=()=>{currentDigestId=Number(button.dataset.digestSelect);renderDigests();});const send=document.querySelector('[data-send-digest]');if(send)send.onclick=async()=>{const card=send.closest('.digest-card'),body=card.querySelector('[data-digest-body]').value;send.disabled=true;try{await request(`/api/admin/digests/${send.dataset.sendDigest}/send`,{method:'POST',body:JSON.stringify({body})});data=await request('/api/admin/overview');render();}catch(error){card.insertAdjacentHTML('beforeend',`<div class="ops-error">${safe(error.message)}</div>`);send.disabled=false;}};}
  document.querySelector('[data-prepare-digest]').onclick=async event=>{const button=event.currentTarget;button.disabled=true;try{const created=await request('/api/admin/digests',{method:'POST',body:'{}'});currentDigestId=created.id;data=await request('/api/admin/overview');render();}finally{button.disabled=false;}};
  const editorialForm=document.querySelector('[data-editorial-form]');
  function campaignCard(item){const variants=Object.entries(item.social_variants||{}).map(([platform,copy])=>`<article class="campaign-variant"><b>${safe(platform)}</b><p>${safe(copy)}</p></article>`).join('');const canApprove=!['approved','ready','blocked'].includes(item.status),canDraft=item.status==='approved';return `<article class="campaign-card"><header><div><span>${safe(item.content_type)}</span><span>${safe(item.status)}</span><span class="risk-${safe(item.risk)}">${safe(item.risk)} risk</span></div><small>${item.scheduled_at?new Date(item.scheduled_at).toLocaleString():'No target date'}</small></header><h3>${safe(item.title||item.brief_title)}</h3><p>${safe(item.excerpt)}</p><small>${safe(item.approval_reason)}</small><details><summary>Blog draft</summary><div class="campaign-variant"><p>${safe(item.blog_body)}</p></div></details><details><summary>Social variants</summary><div class="campaign-variants">${variants}</div></details><footer><small>${safe(item.provider)} · ${(item.input_tokens||0)+(item.output_tokens||0)} tokens</small><div>${canApprove?`<button data-approve-campaign="${item.id}">Approve facts & copy</button>`:''}${canDraft?`<button class="primary" data-journal-campaign="${item.id}">Create journal draft</button>`:''}${item.journal_post_id?'<span>Journal draft created</span>':''}</div></footer>${item.provider_error?`<small>AI fallback: ${safe(item.provider_error)}</small>`:''}</article>`;}
  function renderCampaigns(){const host=document.querySelector('[data-campaign-list]');host.innerHTML=data.campaigns.map(campaignCard).join('')||'<div class="item-card">No campaigns yet. Start with an approved factual brief.</div>';host.querySelectorAll('[data-approve-campaign]').forEach(button=>button.onclick=async()=>{button.disabled=true;try{await request(`/api/admin/editorial/campaigns/${button.dataset.approveCampaign}/approve`,{method:'POST',body:'{}'});data=await request('/api/admin/overview');render();}catch(error){button.closest('.campaign-card').insertAdjacentHTML('beforeend',`<div class="result">${safe(error.message)}</div>`);button.disabled=false;}});host.querySelectorAll('[data-journal-campaign]').forEach(button=>button.onclick=async()=>{button.disabled=true;try{await request(`/api/admin/editorial/campaigns/${button.dataset.journalCampaign}/journal-draft`,{method:'POST',body:'{}'});data=await request('/api/admin/overview');render();}catch(error){button.closest('.campaign-card').insertAdjacentHTML('beforeend',`<div class="result">${safe(error.message)}</div>`);button.disabled=false;}});}
  editorialForm.addEventListener('submit',async event=>{event.preventDefault();const form=event.currentTarget,result=form.querySelector('.result'),button=form.querySelector('button[type="submit"]'),value=form.elements.scheduled_at.value;button.disabled=true;result.textContent='Preparing blog and social drafts…';try{await request('/api/admin/editorial/campaigns',{method:'POST',body:JSON.stringify({brief_title:form.elements.brief_title.value,content_type:form.elements.content_type.value,approved_facts:form.elements.approved_facts.value,audience:form.elements.audience.value,goal:form.elements.goal.value,call_to_action:form.elements.call_to_action.value,scheduled_at:value?new Date(value).toISOString():null})});form.reset();form.elements.call_to_action.value='Learn more at kizuna.technology.';data=await request('/api/admin/overview');render();result.textContent='Campaign prepared.';}catch(error){result.textContent=error.message;}finally{button.disabled=false;}});
  const postForm=document.querySelector('[data-post-form]');
  function renderPosts(){document.querySelector('[data-post-list]').innerHTML=data.posts.map(post=>`<article class="item-card" data-edit-post="${post.id}"><b>${safe(post.title)}</b><small>${safe(post.category)} · Updated ${new Date(post.updated_at).toLocaleDateString()}</small><span>${safe(post.status)}</span></article>`).join('')||'<div class="item-card">No posts yet.</div>';document.querySelectorAll('[data-edit-post]').forEach(card=>card.onclick=()=>editPost(Number(card.dataset.editPost)));}
  function editPost(id=null){const post=data.posts.find(item=>item.id===id);postForm.hidden=false;postForm.reset();postForm.elements.id.value=post?.id||'';postForm.elements.title.value=post?.title||'';postForm.elements.slug.value=post?.slug||'';postForm.elements.category.value=post?.category||'Studio notes';postForm.elements.excerpt.value=post?.excerpt||'';postForm.elements.body.value=post?.body||'';postForm.elements.author.value=post?.author||'Kizuna Studio';postForm.elements.status.value=post?.status||'draft';postForm.elements.featured.checked=Boolean(post?.featured);document.querySelector('[data-editor-title]').textContent=post?'Edit post':'New post';document.querySelector('[data-delete-post]').hidden=!post;}
  document.querySelector('[data-new-post]').onclick=()=>editPost();document.querySelector('[data-cancel-post]').onclick=()=>postForm.hidden=true;
  postForm.addEventListener('submit',async event=>{event.preventDefault();const form=event.currentTarget,id=form.elements.id.value,payload={title:form.elements.title.value,slug:form.elements.slug.value,category:form.elements.category.value,excerpt:form.elements.excerpt.value,body:form.elements.body.value,author:form.elements.author.value,status:form.elements.status.value,featured:form.elements.featured.checked};try{await request(id?`/api/admin/posts/${id}`:'/api/admin/posts',{method:id?'PUT':'POST',body:JSON.stringify(payload)});data=await request('/api/admin/overview');render();editPost(id?Number(id):data.posts[0]?.id);form.querySelector('.result').textContent='Saved.';}catch(error){form.querySelector('.result').textContent=error.message;}});
  document.querySelector('[data-delete-post]').onclick=async()=>{const id=postForm.elements.id.value;if(!id||!confirm('Delete this post? This cannot be undone.'))return;await request(`/api/admin/posts/${id}`,{method:'DELETE'});data=await request('/api/admin/overview');postForm.hidden=true;render();};
  function triageCard(item,type){
    const beta=type==='beta',options=beta?['new','reviewing','invited','waitlisted','closed']:['open','investigating','resolved','closed'];
    const steward=data.account_steward||{records:[]},provisioning=beta?(steward.records||[]).find(record=>record.application_id===item.id):null;
    const accountState=beta?(provisioning?`<small>Account Steward: ${safe(provisioning.status)}${provisioning.error?` · ${safe(provisioning.error)}`:''}</small>`:`<small>Account Steward: ${steward.ready?'ready':'not connected'}</small>`):'';
    const invite=beta&&item.status!=='invited'?`<button type="button" data-beta-invite="${item.id}" ${!steward.ready?'disabled title="Connect Account Steward first"':''}>Invite to beta</button>`:'';
    return `<article class="triage-card"><div><header><span>${safe(beta?item.experience:item.severity)}</span><span>${safe(beta?item.creator_type:item.category)}</span><small>${new Date(item.created_at).toLocaleString()}</small></header><h3>${safe(beta?item.name:item.reference+' · '+item.subject)}</h3><small>${safe(item.email)}</small><p>${safe(beta?item.project_summary:item.description)}</p>${beta&&item.desired_outcome?`<p><b>Desired outcome:</b> ${safe(item.desired_outcome)}</p>`:''}${!beta&&item.environment?`<small>${safe(item.environment)}</small>`:''}${accountState}</div><form data-triage="${type}" data-id="${item.id}"><select name="status">${options.map(option=>`<option value="${option}" ${item.status===option?'selected':''}>${option}</option>`).join('')}</select><textarea name="notes" rows="4" placeholder="Private admin notes">${safe(item.notes)}</textarea><div>${invite}<button type="submit">Save</button></div><div class="result"></div></form></article>`;
  }
  function wireTriage(){
    document.querySelectorAll('[data-triage]').forEach(form=>form.onsubmit=async event=>{event.preventDefault();const type=form.dataset.triage;try{await request(`/api/admin/${type}/${form.dataset.id}`,{method:'PUT',body:JSON.stringify({status:form.elements.status.value,notes:form.elements.notes.value})});form.querySelector('.result').textContent='Saved.';data=await request('/api/admin/overview');render();}catch(error){form.querySelector('.result').textContent=error.message;}});
    document.querySelectorAll('[data-beta-invite]').forEach(button=>button.onclick=async()=>{const form=button.closest('form'),result=form.querySelector('.result');button.disabled=true;result.textContent='Creating a secure invitation…';try{await request(`/api/admin/beta/${button.dataset.betaInvite}/invite`,{method:'POST',body:'{}'});data=await request('/api/admin/overview');render();}catch(error){button.disabled=false;result.textContent=error.message;}});
  }
  function renderBeta(){const filter=document.querySelector('[data-beta-filter]').value;document.querySelector('[data-beta-list]').innerHTML=data.beta.filter(item=>!filter||item.status===filter).map(item=>triageCard(item,'beta')).join('')||'<div class="item-card">No matching applicants.</div>';wireTriage();}
  function renderTickets(){const filter=document.querySelector('[data-ticket-filter]').value;document.querySelector('[data-ticket-list]').innerHTML=data.tickets.filter(item=>!filter||item.status===filter).map(item=>triageCard(item,'tickets')).join('')||'<div class="item-card">No matching tickets.</div>';wireTriage();}
  document.querySelector('[data-beta-filter]').onchange=renderBeta;document.querySelector('[data-ticket-filter]').onchange=renderTickets;load();
})();
