(() => {
  const safe = value => String(value ?? '').replace(/[&<>"']/g, character => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[character]));
  const csrf = () => document.cookie.split('; ').find(item => item.startsWith('kizuna_marketing_csrf='))?.split('=')[1] || '';
  let data = {posts:[],beta:[],tickets:[]};
  const request = async (url, options={}) => { const response=await fetch(url,{...options,headers:{'Content-Type':'application/json','X-Kizuna-CSRF':csrf(),...(options.headers||{})}}); if(response.status===204)return null; const body=await response.json().catch(()=>({})); if(!response.ok)throw new Error(body.detail||'Request failed'); return body; };
  const loginPanel=document.querySelector('[data-login]'),admin=document.querySelector('[data-admin]'),logout=document.querySelector('[data-logout]');
  document.querySelector('[data-login] form').addEventListener('submit',async event=>{event.preventDefault();const result=event.currentTarget.querySelector('[role="status"]');try{await request('/api/admin/login',{method:'POST',body:JSON.stringify({password:event.currentTarget.elements.password.value})});await load();}catch(error){result.textContent=error.message;}});
  logout.addEventListener('click',async()=>{await request('/api/admin/logout',{method:'POST'});location.reload();});
  async function load(){try{data=await request('/api/admin/overview');loginPanel.hidden=true;admin.hidden=false;logout.hidden=false;render();}catch{loginPanel.hidden=false;admin.hidden=true;logout.hidden=true;}}
  function render(){document.querySelector('[data-beta-count]').textContent=data.beta.filter(item=>item.status==='new').length;document.querySelector('[data-ticket-count]').textContent=data.tickets.filter(item=>item.status==='open').length;renderPosts();renderBeta();renderTickets();}
  document.querySelectorAll('[data-view]').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('[data-view]').forEach(item=>item.classList.toggle('active',item===button));document.querySelectorAll('[data-pane]').forEach(pane=>pane.hidden=pane.dataset.pane!==button.dataset.view);}));
  const postForm=document.querySelector('[data-post-form]');
  function renderPosts(){document.querySelector('[data-post-list]').innerHTML=data.posts.map(post=>`<article class="item-card" data-edit-post="${post.id}"><b>${safe(post.title)}</b><small>${safe(post.category)} · Updated ${new Date(post.updated_at).toLocaleDateString()}</small><span>${safe(post.status)}</span></article>`).join('')||'<div class="item-card">No posts yet.</div>';document.querySelectorAll('[data-edit-post]').forEach(card=>card.onclick=()=>editPost(Number(card.dataset.editPost)));}
  function editPost(id=null){const post=data.posts.find(item=>item.id===id);postForm.hidden=false;postForm.reset();postForm.elements.id.value=post?.id||'';postForm.elements.title.value=post?.title||'';postForm.elements.slug.value=post?.slug||'';postForm.elements.category.value=post?.category||'Studio notes';postForm.elements.excerpt.value=post?.excerpt||'';postForm.elements.body.value=post?.body||'';postForm.elements.author.value=post?.author||'Kizuna Studio';postForm.elements.status.value=post?.status||'draft';postForm.elements.featured.checked=Boolean(post?.featured);document.querySelector('[data-editor-title]').textContent=post?'Edit post':'New post';document.querySelector('[data-delete-post]').hidden=!post;}
  document.querySelector('[data-new-post]').onclick=()=>editPost();document.querySelector('[data-cancel-post]').onclick=()=>postForm.hidden=true;
  postForm.addEventListener('submit',async event=>{event.preventDefault();const form=event.currentTarget,id=form.elements.id.value,payload={title:form.elements.title.value,slug:form.elements.slug.value,category:form.elements.category.value,excerpt:form.elements.excerpt.value,body:form.elements.body.value,author:form.elements.author.value,status:form.elements.status.value,featured:form.elements.featured.checked};try{await request(id?`/api/admin/posts/${id}`:'/api/admin/posts',{method:id?'PUT':'POST',body:JSON.stringify(payload)});data=await request('/api/admin/overview');render();editPost(id?Number(id):data.posts[0]?.id);form.querySelector('.result').textContent='Saved.';}catch(error){form.querySelector('.result').textContent=error.message;}});
  document.querySelector('[data-delete-post]').onclick=async()=>{const id=postForm.elements.id.value;if(!id||!confirm('Delete this post? This cannot be undone.'))return;await request(`/api/admin/posts/${id}`,{method:'DELETE'});data=await request('/api/admin/overview');postForm.hidden=true;render();};
  function triageCard(item,type){const beta=type==='beta',options=beta?['new','reviewing','invited','waitlisted','closed']:['open','investigating','resolved','closed'];return `<article class="triage-card"><div><header><span>${safe(beta?item.experience:item.severity)}</span><span>${safe(beta?item.creator_type:item.category)}</span><small>${new Date(item.created_at).toLocaleString()}</small></header><h3>${safe(beta?item.name:item.reference+' · '+item.subject)}</h3><small>${safe(item.email)}</small><p>${safe(beta?item.project_summary:item.description)}</p>${beta&&item.desired_outcome?`<p><b>Desired outcome:</b> ${safe(item.desired_outcome)}</p>`:''}${!beta&&item.environment?`<small>${safe(item.environment)}</small>`:''}</div><form data-triage="${type}" data-id="${item.id}"><select name="status">${options.map(option=>`<option value="${option}" ${item.status===option?'selected':''}>${option}</option>`).join('')}</select><textarea name="notes" rows="4" placeholder="Private admin notes">${safe(item.notes)}</textarea><button type="submit">Save</button><div class="result"></div></form></article>`;}
  function wireTriage(){document.querySelectorAll('[data-triage]').forEach(form=>form.onsubmit=async event=>{event.preventDefault();const type=form.dataset.triage;try{await request(`/api/admin/${type}/${form.dataset.id}`,{method:'PUT',body:JSON.stringify({status:form.elements.status.value,notes:form.elements.notes.value})});form.querySelector('.result').textContent='Saved.';data=await request('/api/admin/overview');render();}catch(error){form.querySelector('.result').textContent=error.message;}});}
  function renderBeta(){const filter=document.querySelector('[data-beta-filter]').value;document.querySelector('[data-beta-list]').innerHTML=data.beta.filter(item=>!filter||item.status===filter).map(item=>triageCard(item,'beta')).join('')||'<div class="item-card">No matching applicants.</div>';wireTriage();}
  function renderTickets(){const filter=document.querySelector('[data-ticket-filter]').value;document.querySelector('[data-ticket-list]').innerHTML=data.tickets.filter(item=>!filter||item.status===filter).map(item=>triageCard(item,'tickets')).join('')||'<div class="item-card">No matching tickets.</div>';wireTriage();}
  document.querySelector('[data-beta-filter]').onchange=renderBeta;document.querySelector('[data-ticket-filter]').onchange=renderTickets;load();
})();
