"""baseline Kizuna schema

Revision ID: b89670b29424
Revises: 
Create Date: 2026-08-09 16:18:42.013090
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'b89670b29424'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Apply this schema revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_model_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider_key', sa.String(length=120), nullable=False),
    sa.Column('model', sa.String(length=255), nullable=False),
    sa.Column('input_per_million', sa.Float(), nullable=False),
    sa.Column('cached_input_per_million', sa.Float(), nullable=False),
    sa.Column('output_per_million', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_key', 'model', name='uq_ai_model_rate')
    )
    op.create_table('ai_provider_routes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task', sa.String(length=80), nullable=False),
    sa.Column('provider_key', sa.String(length=120), nullable=False),
    sa.Column('model_override', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task')
    )
    op.create_table('integration_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=120), nullable=False),
    sa.Column('display_name', sa.String(length=160), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('mode', sa.String(length=32), nullable=False),
    sa.Column('endpoint', sa.Text(), nullable=False),
    sa.Column('model', sa.String(length=255), nullable=False),
    sa.Column('secret_env_var', sa.String(length=160), nullable=False),
    sa.Column('configuration', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('kizuna_nodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('node_key', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('os_name', sa.String(length=80), nullable=False),
    sa.Column('os_version', sa.String(length=160), nullable=False),
    sa.Column('architecture', sa.String(length=40), nullable=False),
    sa.Column('cpu_name', sa.String(length=255), nullable=False),
    sa.Column('logical_cores', sa.Integer(), nullable=False),
    sa.Column('ram_gb', sa.Float(), nullable=False),
    sa.Column('gpu', sa.JSON(), nullable=False),
    sa.Column('software', sa.JSON(), nullable=False),
    sa.Column('benchmark_score', sa.Float(), nullable=False),
    sa.Column('capabilities', sa.JSON(), nullable=False),
    sa.Column('choices', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('last_seen', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('node_key')
    )
    op.create_table('node_enrollments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code_hash')
    )
    op.create_table('professional_identities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.String(length=160), nullable=False),
    sa.Column('legal_name', sa.String(length=200), nullable=False),
    sa.Column('identity_type', sa.String(length=48), nullable=False),
    sa.Column('professional_role', sa.String(length=160), nullable=False),
    sa.Column('website', sa.String(length=1000), nullable=False),
    sa.Column('biography', sa.Text(), nullable=False),
    sa.Column('verification_status', sa.String(length=32), nullable=False),
    sa.Column('verification_evidence', sa.JSON(), nullable=False),
    sa.Column('reviewed_by', sa.String(length=160), nullable=False),
    sa.Column('review_notes', sa.Text(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('logline', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('render_workers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('hostname', sa.String(length=255), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('capabilities', sa.JSON(), nullable=False),
    sa.Column('supported_tasks', sa.JSON(), nullable=False),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('studio_spend_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scope', sa.String(length=40), nullable=False),
    sa.Column('monthly_budget', sa.Float(), nullable=False),
    sa.Column('warning_percent', sa.Integer(), nullable=False),
    sa.Column('hard_stop', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scope')
    )
    op.create_table('workload_policies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task', sa.String(length=80), nullable=False),
    sa.Column('placement', sa.String(length=24), nullable=False),
    sa.Column('node_key', sa.String(length=64), nullable=False),
    sa.Column('cloud_provider', sa.String(length=120), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task')
    )
    op.create_table('ai_usage_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('provider_key', sa.String(length=120), nullable=False),
    sa.Column('model', sa.String(length=255), nullable=False),
    sa.Column('task', sa.String(length=80), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('cached_input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('estimated_cost', sa.Float(), nullable=False),
    sa.Column('pricing_known', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('asset_residencies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('residency_key', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('asset_key', sa.String(length=160), nullable=False),
    sa.Column('representation', sa.String(length=24), nullable=False),
    sa.Column('backend', sa.String(length=24), nullable=False),
    sa.Column('node_key', sa.String(length=64), nullable=False),
    sa.Column('object_ref', sa.Text(), nullable=False),
    sa.Column('uri', sa.Text(), nullable=False),
    sa.Column('checksum_sha256', sa.String(length=64), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('last_verified_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('residency_key')
    )
    op.create_table('asset_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('asset_type', sa.String(length=32), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('selected', sa.Boolean(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_type', 'asset_id', name='uq_asset_review_target')
    )
    op.create_table('asset_rights_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('asset_key', sa.String(length=160), nullable=False),
    sa.Column('source_type', sa.String(length=48), nullable=False),
    sa.Column('rights_holder', sa.String(length=200), nullable=False),
    sa.Column('license_name', sa.String(length=200), nullable=False),
    sa.Column('permitted_uses', sa.JSON(), nullable=False),
    sa.Column('territories', sa.JSON(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('evidence_refs', sa.JSON(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'asset_key', name='uq_asset_rights_project_asset')
    )
    op.create_table('assistant_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('page', sa.String(length=80), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('context', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_ledger_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('previous_hash', sa.String(length=64), nullable=False),
    sa.Column('event_hash', sa.String(length=64), nullable=False),
    sa.Column('category', sa.String(length=48), nullable=False),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('actor_type', sa.String(length=32), nullable=False),
    sa.Column('subject_type', sa.String(length=80), nullable=False),
    sa.Column('subject_key', sa.String(length=180), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_hash'),
    sa.UniqueConstraint('project_id', 'sequence', name='uq_audit_project_sequence')
    )
    op.create_table('backup_schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('interval_hours', sa.Integer(), nullable=False),
    sa.Column('next_run_at', sa.DateTime(), nullable=True),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.Column('last_status', sa.String(length=32), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id')
    )
    op.create_table('characters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('role', sa.String(length=80), nullable=False),
    sa.Column('want', sa.Text(), nullable=False),
    sa.Column('need', sa.Text(), nullable=False),
    sa.Column('contradiction', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('compliance_clearances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('scope', sa.String(length=48), nullable=False),
    sa.Column('confirmed_by', sa.String(length=160), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('evidence_refs', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('compliance_policies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('strict_gates', sa.Boolean(), nullable=False),
    sa.Column('external_clearance_required', sa.Boolean(), nullable=False),
    sa.Column('terms_version', sa.String(length=32), nullable=False),
    sa.Column('accepted_by', sa.String(length=160), nullable=False),
    sa.Column('accepted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id')
    )
    op.create_table('compliance_scans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('stage', sa.String(length=48), nullable=False),
    sa.Column('subject_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('coverage', sa.String(length=32), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=False),
    sa.Column('scanner_version', sa.String(length=32), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('findings', sa.JSON(), nullable=False),
    sa.Column('suggestions', sa.JSON(), nullable=False),
    sa.Column('input_manifest', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('crew_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=48), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('autonomy', sa.String(length=24), nullable=False),
    sa.Column('instructions', sa.Text(), nullable=False),
    sa.Column('capabilities', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('delivery_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('asset_uri', sa.Text(), nullable=False),
    sa.Column('label', sa.String(length=160), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('max_downloads', sa.Integer(), nullable=False),
    sa.Column('download_count', sa.Integer(), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_table('durable_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_key', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.String(length=80), nullable=False),
    sa.Column('queue', sa.String(length=48), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('progress_percent', sa.Integer(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('lease_owner', sa.String(length=120), nullable=False),
    sa.Column('leased_until', sa.DateTime(), nullable=True),
    sa.Column('next_attempt_at', sa.DateTime(), nullable=True),
    sa.Column('cancellation_requested', sa.Boolean(), nullable=False),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_key')
    )
    op.create_table('hive_node_controls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('node_key', sa.String(length=64), nullable=False),
    sa.Column('render_worker_id', sa.Integer(), nullable=True),
    sa.Column('paused', sa.Boolean(), nullable=False),
    sa.Column('drain', sa.Boolean(), nullable=False),
    sa.Column('max_concurrency', sa.Integer(), nullable=False),
    sa.Column('cpu_limit_percent', sa.Integer(), nullable=False),
    sa.Column('gpu_limit_percent', sa.Integer(), nullable=False),
    sa.Column('memory_limit_gb', sa.Float(), nullable=False),
    sa.Column('available_days', sa.JSON(), nullable=False),
    sa.Column('start_hour', sa.Integer(), nullable=False),
    sa.Column('end_hour', sa.Integer(), nullable=False),
    sa.Column('timezone_offset_minutes', sa.Integer(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('allowed_tasks', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['render_worker_id'], ['render_workers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('node_key'),
    sa.UniqueConstraint('render_worker_id')
    )
    op.create_table('media_storage_policies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('original_strategy', sa.String(length=32), nullable=False),
    sa.Column('preferred_node_key', sa.String(length=64), nullable=False),
    sa.Column('keep_server_proxies', sa.Boolean(), nullable=False),
    sa.Column('thumbnail_width', sa.Integer(), nullable=False),
    sa.Column('proxy_width', sa.Integer(), nullable=False),
    sa.Column('minimum_replicas', sa.Integer(), nullable=False),
    sa.Column('evict_server_originals', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id')
    )
    op.create_table('production_scopes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('distribution_channel', sa.String(length=80), nullable=False),
    sa.Column('release_format', sa.String(length=40), nullable=False),
    sa.Column('aspect_ratio', sa.String(length=20), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('target_duration_seconds', sa.Integer(), nullable=False),
    sa.Column('installment_count', sa.Integer(), nullable=False),
    sa.Column('season_count', sa.Integer(), nullable=False),
    sa.Column('story_status', sa.String(length=32), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id')
    )
    op.create_table('professional_work_claims',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('identity_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('work_type', sa.String(length=48), nullable=False),
    sa.Column('credited_role', sa.String(length=160), nullable=False),
    sa.Column('release_year', sa.Integer(), nullable=True),
    sa.Column('external_ids', sa.JSON(), nullable=False),
    sa.Column('evidence_refs', sa.JSON(), nullable=False),
    sa.Column('authorization_scope', sa.Text(), nullable=False),
    sa.Column('verification_status', sa.String(length=32), nullable=False),
    sa.Column('reviewed_by', sa.String(length=160), nullable=False),
    sa.Column('review_notes', sa.Text(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['identity_id'], ['professional_identities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_backups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('storage_key', sa.Text(), nullable=False),
    sa.Column('checksum_sha256', sa.String(length=64), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('asset_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_milestones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=48), nullable=False),
    sa.Column('completed_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'key', name='uq_project_milestone_key')
    )
    op.create_table('scenes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('storage_policies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('backend', sa.String(length=32), nullable=False),
    sa.Column('retention_days', sa.Integer(), nullable=False),
    sa.Column('max_backups', sa.Integer(), nullable=False),
    sa.Column('include_media', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id')
    )
    op.create_table('story_briefs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('premise', sa.Text(), nullable=False),
    sa.Column('format', sa.String(length=32), nullable=False),
    sa.Column('target_duration_minutes', sa.Integer(), nullable=False),
    sa.Column('audience', sa.String(length=80), nullable=False),
    sa.Column('genre', sa.String(length=80), nullable=False),
    sa.Column('themes', sa.JSON(), nullable=False),
    sa.Column('synopsis', sa.Text(), nullable=False),
    sa.Column('beats', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id')
    )
    op.create_table('style_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('era_primary', sa.String(length=64), nullable=False),
    sa.Column('era_secondary', sa.String(length=64), nullable=False),
    sa.Column('visual', sa.JSON(), nullable=False),
    sa.Column('direction', sa.JSON(), nullable=False),
    sa.Column('narrative', sa.JSON(), nullable=False),
    sa.Column('archetypes', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id')
    )
    op.create_table('timelines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('fps', sa.Integer(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id')
    )
    op.create_table('world_locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('narrative_function', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('geography', sa.String(length=160), nullable=False),
    sa.Column('time_period', sa.String(length=120), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('animatic_renders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timeline_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('uri', sa.Text(), nullable=False),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('render_settings', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['timeline_id'], ['timelines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audio_tracks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timeline_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('volume', sa.Float(), nullable=False),
    sa.Column('muted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['timeline_id'], ['timelines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('background_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('negative_prompt', sa.Text(), nullable=False),
    sa.Column('external_id', sa.String(length=160), nullable=False),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('result_data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['world_locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('character_designs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('appearance', sa.JSON(), nullable=False),
    sa.Column('palette', sa.JSON(), nullable=False),
    sa.Column('wardrobe', sa.JSON(), nullable=False),
    sa.Column('consistency_anchors', sa.JSON(), nullable=False),
    sa.Column('reference_brief', sa.Text(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('character_id')
    )
    op.create_table('character_relationships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('target_character_id', sa.Integer(), nullable=False),
    sa.Column('relationship_type', sa.String(length=80), nullable=False),
    sa.Column('public_dynamic', sa.Text(), nullable=False),
    sa.Column('private_truth', sa.Text(), nullable=False),
    sa.Column('tension', sa.Text(), nullable=False),
    sa.Column('arc', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ),
    sa.ForeignKeyConstraint(['target_character_id'], ['characters.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('character_id', 'target_character_id', name='uq_character_relationship_target')
    )
    op.create_table('character_story_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('history', sa.Text(), nullable=False),
    sa.Column('formative_event', sa.Text(), nullable=False),
    sa.Column('secret', sa.Text(), nullable=False),
    sa.Column('fear', sa.Text(), nullable=False),
    sa.Column('misbelief', sa.Text(), nullable=False),
    sa.Column('arc_start', sa.Text(), nullable=False),
    sa.Column('arc_turn', sa.Text(), nullable=False),
    sa.Column('arc_end', sa.Text(), nullable=False),
    sa.Column('stakes', sa.Text(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('character_id')
    )
    op.create_table('compliance_finding_resolutions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scan_id', sa.Integer(), nullable=False),
    sa.Column('finding_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('reviewer', sa.String(length=160), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('evidence_refs', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['scan_id'], ['compliance_scans.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scan_id', 'finding_id', name='uq_compliance_scan_finding_resolution')
    )
    op.create_table('compliance_provider_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scan_id', sa.Integer(), nullable=False),
    sa.Column('provider_key', sa.String(length=120), nullable=False),
    sa.Column('category', sa.String(length=48), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('response_hash', sa.String(length=64), nullable=False),
    sa.Column('matches', sa.JSON(), nullable=False),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['scan_id'], ['compliance_scans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('crew_actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('assignment_id', sa.Integer(), nullable=True),
    sa.Column('role', sa.String(length=48), nullable=False),
    sa.Column('action_type', sa.String(length=80), nullable=False),
    sa.Column('title', sa.String(length=180), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('requires_approval', sa.Boolean(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assignment_id'], ['crew_assignments.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('durable_job_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('progress_percent', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=False),
    sa.Column('event_data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['durable_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('generation_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('negative_prompt', sa.Text(), nullable=False),
    sa.Column('external_id', sa.String(length=160), nullable=False),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('request_data', sa.JSON(), nullable=False),
    sa.Column('result_data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('location_designs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('appearance', sa.JSON(), nullable=False),
    sa.Column('palette', sa.JSON(), nullable=False),
    sa.Column('layers', sa.JSON(), nullable=False),
    sa.Column('lighting_variants', sa.JSON(), nullable=False),
    sa.Column('continuity_anchors', sa.JSON(), nullable=False),
    sa.Column('reference_brief', sa.Text(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['world_locations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('location_id')
    )
    op.create_table('master_export_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timeline_id', sa.Integer(), nullable=False),
    sa.Column('profile', sa.String(length=32), nullable=False),
    sa.Column('fps', sa.Integer(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('final_filename', sa.String(length=255), nullable=False),
    sa.Column('final_uri', sa.Text(), nullable=False),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['timeline_id'], ['timelines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('media_cleanup_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('asset_key', sa.String(length=160), nullable=False),
    sa.Column('source_residency_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('checksum_sha256', sa.String(length=64), nullable=False),
    sa.Column('required_replicas', sa.Integer(), nullable=False),
    sa.Column('verified_replicas', sa.Integer(), nullable=False),
    sa.Column('verification_cutoff', sa.DateTime(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['source_residency_id'], ['asset_residencies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'asset_key', name='uq_media_cleanup_review')
    )
    op.create_table('media_transfer_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_key', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('asset_key', sa.String(length=160), nullable=False),
    sa.Column('source_residency_id', sa.Integer(), nullable=False),
    sa.Column('target_node_key', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('expected_checksum_sha256', sa.String(length=64), nullable=False),
    sa.Column('expected_size_bytes', sa.Integer(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('leased_until', sa.DateTime(), nullable=True),
    sa.Column('object_ref', sa.Text(), nullable=False),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['source_residency_id'], ['asset_residencies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_key')
    )
    op.create_table('professional_verification_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('identity_id', sa.Integer(), nullable=False),
    sa.Column('work_claim_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('actor', sa.String(length=160), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['identity_id'], ['professional_identities.id'], ),
    sa.ForeignKeyConstraint(['work_claim_id'], ['professional_work_claims.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pronunciation_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=True),
    sa.Column('term', sa.String(length=160), nullable=False),
    sa.Column('pronunciation', sa.String(length=240), nullable=False),
    sa.Column('language', sa.String(length=40), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scene_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['scene_id'], ['scenes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('voice_consents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.String(length=48), nullable=False),
    sa.Column('subject_name', sa.String(length=160), nullable=False),
    sa.Column('consent_confirmed', sa.Boolean(), nullable=False),
    sa.Column('disclosure_required', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('voice_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('vocal_age', sa.String(length=80), nullable=False),
    sa.Column('texture', sa.String(length=120), nullable=False),
    sa.Column('energy', sa.String(length=120), nullable=False),
    sa.Column('accent', sa.String(length=120), nullable=False),
    sa.Column('language', sa.String(length=40), nullable=False),
    sa.Column('pace', sa.Float(), nullable=False),
    sa.Column('pitch', sa.Float(), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('provider_voice_id', sa.String(length=160), nullable=False),
    sa.Column('direction_notes', sa.Text(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('character_id')
    )
    op.create_table('background_assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('background_job_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('uri', sa.Text(), nullable=False),
    sa.Column('mime_type', sa.String(length=80), nullable=False),
    sa.Column('asset_metadata', sa.JSON(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['background_job_id'], ['background_jobs.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['world_locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('master_segments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('export_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('worker_id', sa.Integer(), nullable=True),
    sa.Column('leased_until', sa.DateTime(), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('uri', sa.Text(), nullable=False),
    sa.Column('checksum_sha256', sa.String(length=64), nullable=False),
    sa.Column('manifest', sa.JSON(), nullable=False),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['export_id'], ['master_export_jobs.id'], ),
    sa.ForeignKeyConstraint(['worker_id'], ['render_workers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('media_assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=True),
    sa.Column('generation_job_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.String(length=48), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('uri', sa.Text(), nullable=False),
    sa.Column('mime_type', sa.String(length=80), nullable=False),
    sa.Column('asset_metadata', sa.JSON(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ),
    sa.ForeignKeyConstraint(['generation_job_id'], ['generation_jobs.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('production_workflows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('objective', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('current_stage', sa.String(length=48), nullable=False),
    sa.Column('stages', sa.JSON(), nullable=False),
    sa.Column('settings', sa.JSON(), nullable=False),
    sa.Column('last_action_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['last_action_id'], ['crew_actions.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id')
    )
    op.create_table('shot_compositions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shot_id', sa.Integer(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('camera', sa.JSON(), nullable=False),
    sa.Column('color_grade', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['shot_id'], ['shots.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shot_id')
    )
    op.create_table('shot_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shot_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('character_ids', sa.JSON(), nullable=False),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('dialogue', sa.Text(), nullable=False),
    sa.Column('camera', sa.JSON(), nullable=False),
    sa.Column('lighting', sa.String(length=160), nullable=False),
    sa.Column('continuity_notes', sa.Text(), nullable=False),
    sa.Column('storyboard_prompt', sa.Text(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['world_locations.id'], ),
    sa.ForeignKeyConstraint(['shot_id'], ['shots.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shot_id')
    )
    op.create_table('storyboard_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shot_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('negative_prompt', sa.Text(), nullable=False),
    sa.Column('external_id', sa.String(length=160), nullable=False),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('result_data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['shot_id'], ['shots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('timeline_clips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timeline_id', sa.Integer(), nullable=False),
    sa.Column('shot_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=False),
    sa.Column('transition', sa.String(length=32), nullable=False),
    sa.Column('transition_duration', sa.Float(), nullable=False),
    sa.Column('audio_cue', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['shot_id'], ['shots.id'], ),
    sa.ForeignKeyConstraint(['timeline_id'], ['timelines.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shot_id')
    )
    op.create_table('worker_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('generation_job_id', sa.Integer(), nullable=False),
    sa.Column('worker_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('leased_until', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['generation_job_id'], ['generation_jobs.id'], ),
    sa.ForeignKeyConstraint(['worker_id'], ['render_workers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('generation_job_id')
    )
    op.create_table('audio_cues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.Column('clip_id', sa.Integer(), nullable=True),
    sa.Column('character_id', sa.Integer(), nullable=True),
    sa.Column('start_seconds', sa.Float(), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('direction', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('uri', sa.Text(), nullable=False),
    sa.Column('mime_type', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ),
    sa.ForeignKeyConstraint(['clip_id'], ['timeline_clips.id'], ),
    sa.ForeignKeyConstraint(['track_id'], ['audio_tracks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('composite_renders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('composition_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('uri', sa.Text(), nullable=False),
    sa.Column('mime_type', sa.String(length=80), nullable=False),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('render_settings', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['composition_id'], ['shot_compositions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('composition_layers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('composition_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('source_kind', sa.String(length=48), nullable=False),
    sa.Column('source_asset_id', sa.Integer(), nullable=True),
    sa.Column('source_uri', sa.Text(), nullable=False),
    sa.Column('z_index', sa.Integer(), nullable=False),
    sa.Column('visible', sa.Boolean(), nullable=False),
    sa.Column('opacity', sa.Float(), nullable=False),
    sa.Column('blend_mode', sa.String(length=32), nullable=False),
    sa.Column('transform', sa.JSON(), nullable=False),
    sa.Column('animation', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['composition_id'], ['shot_compositions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shot_motion_renders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('composition_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('uri', sa.Text(), nullable=False),
    sa.Column('mime_type', sa.String(length=80), nullable=False),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('render_settings', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['composition_id'], ['shot_compositions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('storyboard_assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shot_id', sa.Integer(), nullable=False),
    sa.Column('storyboard_job_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('uri', sa.Text(), nullable=False),
    sa.Column('mime_type', sa.String(length=80), nullable=False),
    sa.Column('asset_metadata', sa.JSON(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['shot_id'], ['shots.id'], ),
    sa.ForeignKeyConstraint(['storyboard_job_id'], ['storyboard_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert this schema revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('storyboard_assets')
    op.drop_table('shot_motion_renders')
    op.drop_table('composition_layers')
    op.drop_table('composite_renders')
    op.drop_table('audio_cues')
    op.drop_table('worker_assignments')
    op.drop_table('timeline_clips')
    op.drop_table('storyboard_jobs')
    op.drop_table('shot_plans')
    op.drop_table('shot_compositions')
    op.drop_table('production_workflows')
    op.drop_table('media_assets')
    op.drop_table('master_segments')
    op.drop_table('background_assets')
    op.drop_table('voice_profiles')
    op.drop_table('voice_consents')
    op.drop_table('shots')
    op.drop_table('pronunciation_entries')
    op.drop_table('professional_verification_events')
    op.drop_table('media_transfer_jobs')
    op.drop_table('media_cleanup_reviews')
    op.drop_table('master_export_jobs')
    op.drop_table('location_designs')
    op.drop_table('generation_jobs')
    op.drop_table('durable_job_events')
    op.drop_table('crew_actions')
    op.drop_table('compliance_provider_results')
    op.drop_table('compliance_finding_resolutions')
    op.drop_table('character_story_profiles')
    op.drop_table('character_relationships')
    op.drop_table('character_designs')
    op.drop_table('background_jobs')
    op.drop_table('audio_tracks')
    op.drop_table('animatic_renders')
    op.drop_table('world_locations')
    op.drop_table('timelines')
    op.drop_table('style_profiles')
    op.drop_table('story_briefs')
    op.drop_table('storage_policies')
    op.drop_table('scenes')
    op.drop_table('project_milestones')
    op.drop_table('project_backups')
    op.drop_table('professional_work_claims')
    op.drop_table('production_scopes')
    op.drop_table('media_storage_policies')
    op.drop_table('hive_node_controls')
    op.drop_table('durable_jobs')
    op.drop_table('delivery_links')
    op.drop_table('crew_assignments')
    op.drop_table('compliance_scans')
    op.drop_table('compliance_policies')
    op.drop_table('compliance_clearances')
    op.drop_table('characters')
    op.drop_table('backup_schedules')
    op.drop_table('audit_ledger_events')
    op.drop_table('assistant_messages')
    op.drop_table('asset_rights_records')
    op.drop_table('asset_reviews')
    op.drop_table('asset_residencies')
    op.drop_table('ai_usage_events')
    op.drop_table('workload_policies')
    op.drop_table('studio_spend_settings')
    op.drop_table('render_workers')
    op.drop_table('projects')
    op.drop_table('professional_identities')
    op.drop_table('node_enrollments')
    op.drop_table('kizuna_nodes')
    op.drop_table('integration_profiles')
    op.drop_table('ai_provider_routes')
    op.drop_table('ai_model_rates')
    # ### end Alembic commands ###
